part1-Dataset Exploration

In [ ]:
import pandas as pd
data = {
    "Study_Hours":[1,2,3,4,5,6,7,8,9,10,11,12],
    "Attendance":[60,65,70,72,75,80,82,85,88,90,92,95],
    "Assignments":[2,3,4,5,5,6,7,7,8,8,9,10],
    "Marks":[35,40,45,50,58,65,72,78,82,88,92,96]
}
df = pd.DataFrame(data)
df. to_csv("student_performance.csv",index=False)

In [ ]:
import pandas as pd
df=pd.read_csv("student_performance.csv")
df.head()

   Study_Hours  Attendance  Assignments  Marks
0            1          60            2     35
1            2          65            3     40
2            3          70            4     45
3            4          72            5     50
4            5          75            5     58

In [ ]:
df.tail()

    Study_Hours  Attendance  Assignments  Marks
7             8          85            7     78
8             9          88            8     82
9            10          90            8     88
10           11          92            9     92
11           12          95           10     96

In [ ]:
df.shape

(12, 4)

In [ ]:
df.columns

Index(['Study_Hours', 'Attendance', 'Assignments', 'Marks'], dtype='object')

In [ ]:
df.dtypes

Study_Hours    int64
Attendance     int64
Assignments    int64
Marks          int64
dtype: object

In [ ]:
df.describe()

       Study_Hours  Attendance  Assignments      Marks
count    12.000000   12.000000    12.000000  12.000000
mean      6.500000   79.500000     6.166667  66.750000
std       3.605551   11.172206     2.443296  21.080474
min       1.000000   60.000000     2.000000  35.000000
25%       3.750000   71.500000     4.750000  48.750000
50%       6.500000   81.000000     6.500000  68.500000
75%       9.250000   88.500000     8.000000  83.500000
max      12.000000   95.000000    10.000000  96.000000

# Part-2 Identify Features and Label

In [ ]:
# Features (Input variables)
x = df[['Study_Hours', 'Attendance', 'Assignments']]

# Label (Target variable)
y = df['Marks']

# Print them
print("Features (x):")
print(x)

print("\nLabel (y):")
print(y)

Features (x):
    Study_Hours  Attendance  Assignments
0             1          60            2
1             2          65            3
2             3          70            4
3             4          72            5
4             5          75            5
5             6          80            6
6             7          82            7
7             8          85            7
8             9          88            8
9            10          90            8
10           11          92            9
11           12          95           10

Label (y):
0     35
1     40
2     45
3     50
4     58
5     65
6     72
7     78
8     82
9     88
10    92
11    96
Name: Marks, dtype: int64

part4-Train-test Split

In [ ]:
#Training data(80%)-> used to teach model
#Testing data(20%)->used to check how well the model performs on unseen data
from sklearn.model_selection import train_test_split
# Features
x = df[['Study_Hours', 'Attendance', 'Assignments']]
# Label
y = df['Marks']
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=42)
print("x_train shape:", x_train.shape)
print("x_test shape:", x_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

x_train shape: (9, 3)
x_test shape: (3, 3)
y_train shape: (9,)
y_test shape: (3,)

Part5-Train Your first model

In [ ]:
from sklearn.linear_model import LinearRegression
model= LinearRegression()
print(model)

LinearRegression()

In [ ]:
model=LinearRegression()
model.fit(x_train,y_train)
print("Slope(coefficients):")
print(model.coef_)

Slope(coefficients):
[ 3.45487968  1.34491979 -2.40274064]

In [ ]:
print("Intercept:")
print(model.intercept_)

Intercept:
-48.100601604278054

part6-Predictions

In [ ]:
predictions=model.predict(x_test)
print(predictions)

[92.01102941 88.2690508  31.24398396]

In [ ]:
from sklearn.linear_model import LinearRegression
model= LinearRegression()
model.fit(x_train,y_train)
new_data=pd.DataFrame({
  'Study_Hours':[5,8,12],
  'Attendance':[80,90,95],
  'Assignments':[5,8,10]

})
model.fit(x_train,y_train)
predictions=model.predict(new_data)
print("Predicted Marks:")
print(predictions)

Predicted Marks:
[64.75367647 81.35929144 97.09792781]

part7-Actual vs Predicted Comparison

In [ ]:
y_pred=model.predict(x_test)
import pandas as pd
comparison = pd.DataFrame({
    'Actual Marks': y_test,
    'Predicted Marks': y_pred,
    'Difference': abs(y_test - y_pred)
})

print(comparison)
Difference= y_test-y_pred

    Actual Marks  Predicted Marks  Difference
10            92        92.011029    0.011029
9             88        88.269051    0.269051
0             35        31.243984    3.756016

In [ ]:
print(comparison['Difference'].max())

3.7560160427807574

part8-Model Evaluation

In [ ]:
from sklearn.metrics import mean_absolute_error, r2_score
y_pred=model.predict(x_test)
mae=mean_absolute_error(y_test,y_pred)
print("Mean Absolute Error:",mae)
r2=r2_score(y_test,y_pred)
print("R^2 Score:",r2)

Mean Absolute Error: 1.3453654188948245
R^2 Score: 0.9929962957709836

part9-Data Visulization Challenge

In [ ]:
#plot 1
fig = px.scatter(
    df,
    x='Study_Hours',
    y='Marks',
    title='Study Hours vs Marks',
    labels={
        'Study_Hours': 'Study Hours',
        'Marks': 'Marks'
    }
)

fig.show()

In [ ]:
#plot 2
fig = px.scatter(
    df,
    x='Attendance',
    y='Marks',
    title='Attendance vs Marks',
    hover_data=['Study_Hours', 'Assignments']
)

fig.show()

In [ ]:
#plot 3
fig = px.scatter(
    df,
    x='Assignments',
    y='Marks',
    title='Assignments vs Marks',
    color='Assignments'
)

fig.show()

In [ ]:
#plot 4
fig = px.scatter(
    df,
    x='Study_Hours',
    y='Marks',
    trendline='ols',
    title='Regression Line Visualization'
)

fig.show()

In [ ]:
#plot5
study_hours = list(range(1, 16))

In [ ]:
import pandas as pd

new_data = pd.DataFrame({
    'Study_Hours': study_hours,
    'Attendance': [90] * 15,
    'Assignments': [8] * 15
})

In [ ]:
predicted_marks = model.predict(new_data)

In [ ]:
fig = px.line(
    x=study_hours,
    y=predicted_marks,
    title='Predicted Marks Trend',
    labels={
        'x': 'Study Hours',
        'y': 'Predicted Marks'
    }
)

fig.show()